// Revolve: a V-groove pulley generated by revolving a 2D profile about the Z axis.
// The profile is a closed planar face in the XZ plane (x = radius, z = height), built with
// polygon() — a typed OrientedFace — rather than draw().close().sketchOnPlane('XZ').face().
// `sketchOnPlane()` returns `SketchInterface | Sketches`, and `.face()` is not on the
// multi-profile branch, so the draw path fails `--check`. polygon() keeps the part type-clean.
import { polygon, revolve, unwrap } from 'brepjs';

const BORE_RADIUS = 4; // mm — central shaft hole radius
const HUB_RADIUS = 18; // mm — outer rim radius
const GROOVE_RADIUS = 12; // mm — depth of the V groove (inner radius)
const HEIGHT = 10; // mm — total axial height
const FULL_TURN = Math.PI * 2; // revolve angle — occt-wasm reads this in RADIANS, not degrees

export default () => {
  // Half cross-section (y = 0): up the bore, out along the bottom, in for the V-groove, back.
  const profile = unwrap(
    polygon([
      [BORE_RADIUS, 0, 0],
      [HUB_RADIUS, 0, 0],
      [HUB_RADIUS, 0, HEIGHT * 0.25],
      [GROOVE_RADIUS, 0, HEIGHT * 0.5],
      [HUB_RADIUS, 0, HEIGHT * 0.75],
      [HUB_RADIUS, 0, HEIGHT],
      [BORE_RADIUS, 0, HEIGHT],
    ])
  );

  return revolve(profile, { axis: [0, 0, 1], at: [0, 0, 0], angle: FULL_TURN });
};
