/**
 * Type-safe interface for the brepkit WASM kernel (`BrepKernel`).
 *
 * AUTO-GENERATED by `npm run sync:brepkit-types`.
 * Synced against `brepkit-wasm@2.101.1`.
 *
 * Methods not yet referenced in the adapter layer are tagged `@unwired`.
 *
 * @module
 */

// ── Mesh result from tessellation ────────────────────────────────

/** Triangle mesh returned by `tessellateFace` / `tessellateSolid`. */
export interface BrepkitMesh {
  /** Flattened vertex positions `[x, y, z, ...]`. */
  readonly positions: Float64Array;
  /** Flattened per-vertex normals `[nx, ny, nz, ...]`. */
  readonly normals: Float64Array;
  /** Triangle indices (groups of 3). */
  readonly indices: Uint32Array;
  /** Number of vertices. */
  readonly vertexCount: number;
  /** Number of triangles. */
  readonly triangleCount: number;
  /** All mesh data in a single packed buffer for efficient FFI transfer. */
  packedBuffer(): Uint8Array;
}

/** Edge polylines returned by `meshEdges`. */
export interface BrepkitEdgeLines {
  /** Flattened vertex positions `[x, y, z, ...]`. */
  readonly positions: Float64Array;
  /** Start index into positions for each edge polyline (already ×3). */
  readonly offsets: Uint32Array;
  /** Number of edges. */
  readonly edgeCount: number;
}

// ── Main kernel interface ────────────────────────────────────────

/**
 * Type-safe view of brepkit's WASM `BrepKernel` class.
 *
 * All handle parameters and return values are `number` (u32 arena indices).
 * Coordinate arrays are flat `number[]` (`[x,y,z, ...]`).
 * Matrices are 16-element row-major `number[]`.
 */
export interface BrepkitKernel {
  // ── Primitives ────────────────────────────────────────────────

  makeBox(dx: number, dy: number, dz: number): number;

  makeCylinder(radius: number, height: number): number;

  makeSphere(radius: number, segments: number): number;

  makeCone(bottomRadius: number, topRadius: number, height: number): number;

  makeTorus(majorRadius: number, minorRadius: number, segments: number): number;

  /** @unwired */
  makeEllipsoid(rx: number, ry: number, rz: number): number;

  makeRectangle(width: number, height: number): number;

  /** @unwired */
  makePolygon(coords: Float64Array | number[]): number;

  /** @unwired */
  makeCircle(radius: number, segments: number): number;

  /** @unwired */
  makeCircleFace(radius: number, segments: number): number;

  // ── Shape construction ────────────────────────────────────────

  makeVertex(x: number, y: number, z: number): number;

  makeLineEdge(x1: number, y1: number, z1: number, x2: number, y2: number, z2: number): number;

  makeCircleArc3d(
    startX: number,
    startY: number,
    startZ: number,
    endX: number,
    endY: number,
    endZ: number,
    centerX: number,
    centerY: number,
    centerZ: number,
    axisX: number,
    axisY: number,
    axisZ: number
  ): number;

  makeTangentArc3d(
    startX: number,
    startY: number,
    startZ: number,
    tangentX: number,
    tangentY: number,
    tangentZ: number,
    endX: number,
    endY: number,
    endZ: number
  ): number;

  makeNurbsEdge(
    startX: number,
    startY: number,
    startZ: number,
    endX: number,
    endY: number,
    endZ: number,
    degree: number,
    knots: Float64Array | number[],
    controlPoints: Float64Array | number[],
    weights: Float64Array | number[]
  ): number;

  makeWire(edgeHandles: Uint32Array | number[], closed: boolean): number;

  makePolygonWire(coords: Float64Array | number[]): number;

  /** @unwired */
  makeRegularPolygonWire(radius: number, nSides: number): number;

  makeFaceFromWire(wire: number): number;

  makeCompound(solidHandles: Uint32Array | number[]): number;

  /** @unwired */
  makeSolid(faceHandles: Uint32Array | number[]): number;

  solidFromShell(shell: number): number;

  addHolesToFace(face: number, holeWireHandles: Uint32Array | number[]): number;

  removeHolesFromFace(face: number): number;

  reverseShape(id: number): number;

  // ── Boolean ops ───────────────────────────────────────────────

  fuse(a: number, b: number): number;

  cut(a: number, b: number): number;

  intersect(a: number, b: number): number;

  compoundCut(target: number, toolIds: Uint32Array | number[]): number;

  convexHull(coords: Float64Array | number[]): number;

  section(
    solid: number,
    px: number,
    py: number,
    pz: number,
    nx: number,
    ny: number,
    nz: number
  ): Uint32Array;

  split(
    solid: number,
    px: number,
    py: number,
    pz: number,
    nx: number,
    ny: number,
    nz: number
  ): Uint32Array;

  // ── Evolution tracking ────────────────────────────────────────

  fuseWithEvolution(a: number, b: number): string;

  cutWithEvolution(a: number, b: number): string;

  intersectWithEvolution(a: number, b: number): string;

  // ── Sweep / Loft ──────────────────────────────────────────────

  extrude(face: number, dirX: number, dirY: number, dirZ: number, distance: number): number;

  revolve(
    face: number,
    ox: number,
    oy: number,
    oz: number,
    dx: number,
    dy: number,
    dz: number,
    angleDegrees: number
  ): number;

  sweep(
    face: number,
    pathDegree: number,
    pathKnots: Float64Array | number[],
    pathControlPoints: Float64Array | number[],
    pathWeights: Float64Array | number[]
  ): number;

  sweepSmooth(
    face: number,
    pathDegree: number,
    pathKnots: Float64Array | number[],
    pathControlPoints: Float64Array | number[],
    pathWeights: Float64Array | number[]
  ): number;

  sweepAlongEdges(face: number, edgeHandles: Uint32Array | number[]): number;

  sweepWithOptions(
    profile: number,
    pathEdge: number,
    contactMode: string,
    scaleValues: Float64Array | number[],
    segments: number,
    cornerMode: string
  ): number;

  pipe(
    face: number,
    pathDegree: number,
    pathKnots: Float64Array | number[],
    pathControlPoints: Float64Array | number[],
    pathWeights: Float64Array | number[]
  ): number;

  loft(faces: Uint32Array | number[]): number;

  loftSmooth(faces: Uint32Array | number[]): number;

  loftWithOptions(faces: Uint32Array | number[], options: string): number;

  helicalSweep(
    profile: number,
    axisOriginX: number,
    axisOriginY: number,
    axisOriginZ: number,
    axisDirX: number,
    axisDirY: number,
    axisDirZ: number,
    radius: number,
    pitch: number,
    turns: number
  ): number;

  // ── Modifiers ─────────────────────────────────────────────────

  fillet(solid: number, edgeHandles: Uint32Array | number[], radius: number): number;

  /** @unwired */
  filletV2(solid: number, edgeHandles: Uint32Array | number[], radius: number): number;

  filletVariable(solid: number, json: string): number;

  chamfer(solid: number, edgeHandles: Uint32Array | number[], distance: number): number;

  /** @unwired */
  chamferV2(solid: number, edgeHandles: Uint32Array | number[], d1: number, d2: number): number;

  /** @unwired */
  chamferDistanceAngle(
    solid: number,
    edgeHandles: Uint32Array | number[],
    distance: number,
    angle: number
  ): number;

  shell(solid: number, thickness: number, openFaces: Uint32Array | number[]): number;

  /** @unwired */
  offsetSolid(solid: number, distance: number): number;

  offsetSolidV2(solid: number, distance: number): number;

  /** @unwired */
  offsetFace(face: number, distance: number, samples: number): number;

  /** @unwired */
  offsetWire(face: number, distance: number): number;

  /** @unwired */
  offsetWireWithJoinType(face: number, distance: number, joinType: string): number;

  thicken(face: number, thickness: number): number;

  draft(
    solid: number,
    faceHandles: Uint32Array | number[],
    pullX: number,
    pullY: number,
    pullZ: number,
    neutralX: number,
    neutralY: number,
    neutralZ: number,
    angleDegrees: number
  ): number;

  defeature(solid: number, faceHandles: Uint32Array | number[]): number;

  detectSmallFeatures(solid: number, areaThreshold: number, deflection: number): Uint32Array;

  recognizeFeatures(solid: number, deflection: number): string;

  /** @unwired */
  unifyFaces(solid: number): number;

  // ── Transform ─────────────────────────────────────────────────

  transformSolid(solid: number, matrix: Float64Array | number[]): void;

  transformWire(wire: number, matrix: Float64Array | number[]): void;

  copySolid(solid: number): number;

  copyWire(wire: number): number;

  /** @unwired */
  copyAndTransformSolid(solid: number, matrix: Float64Array | number[]): number;

  mirror(
    solid: number,
    px: number,
    py: number,
    pz: number,
    nx: number,
    ny: number,
    nz: number
  ): number;

  /** @unwired */
  linearPattern(
    solid: number,
    dx: number,
    dy: number,
    dz: number,
    spacing: number,
    count: number
  ): number;

  /** @unwired */
  circularPattern(solid: number, ax: number, ay: number, az: number, count: number): number;

  gridPattern(
    solid: number,
    dirXX: number,
    dirXY: number,
    dirXZ: number,
    dirYX: number,
    dirYY: number,
    dirYZ: number,
    spacingX: number,
    spacingY: number,
    countX: number,
    countY: number
  ): number;

  composeTransforms(
    matrixA: Float64Array | number[],
    matrixB: Float64Array | number[]
  ): Float64Array;

  // ── Sewing ────────────────────────────────────────────────────

  sewFaces(faceHandles: Uint32Array | number[], tolerance: number): number;

  weldShellsAndFaces(faceHandles: Uint32Array | number[], tolerance: number): number;

  fillCoonsPatch(
    boundaryCoords: Float64Array | number[],
    curveLengths: Uint32Array | number[]
  ): number;

  untrimFace(face: number, samplesPerCurve: number, interiorSamples: number): number;

  // ── Topology ──────────────────────────────────────────────────

  getSolidFaces(solid: number): Uint32Array;

  getSolidEdges(solid: number): Uint32Array;

  getSolidVertices(solid: number): Uint32Array;

  getFaceEdges(face: number): Uint32Array;

  getFaceVertices(face: number): Uint32Array;

  getFaceNormal(face: number): Float64Array;

  getFaceOuterWire(face: number): number;

  getFaceWires(face: number): Uint32Array;

  /** @unwired */
  faceWires(face: number): Uint32Array;

  getWireEdges(wire: number): Uint32Array;

  getEdgeVertices(edge: number): Float64Array;

  /** @unwired */
  getEdgeVertexHandles(edge: number): Uint32Array;

  getVertexPosition(vertex: number): Float64Array;

  /** @unwired */
  getEntityCounts(solid: number): Uint32Array;

  getShellFaces(shell: number): Uint32Array;

  getShapeOrientation(_id: number): string;

  adjacentFaces(solid: number, face: number): Uint32Array;

  sharedEdges(faceA: number, faceB: number): Uint32Array;

  edgeToFaceMap(solid: number): string;

  /** @unwired */
  isEdgeForwardInWire(edge: number, wire: number): boolean;

  /** @unwired */
  isWireClosed(wire: number): boolean;

  getCompoundSolids(compound: number): Uint32Array;

  // ── Geometry ──────────────────────────────────────────────────

  getSurfaceType(face: number): string;

  getSurfaceDomain(face: number): Float64Array;

  getAnalyticSurfaceParams(face: number): string;

  getEdgeCurveType(edge: number): string;

  getEdgeCurveParameters(edge: number): Float64Array;

  getEdgeNurbsData(edge: number): string | null;

  evaluateEdgeCurve(edge: number, t: number): Float64Array;

  evaluateEdgeCurveD1(edge: number, t: number): Float64Array;

  evaluateSurface(face: number, u: number, v: number): Float64Array;

  evaluateSurfaceNormal(face: number, u: number, v: number): Float64Array;

  projectPointOnSurface(face: number, px: number, py: number, pz: number): Float64Array;

  /** @unwired */
  liftCurve2dToPlane(
    curveType: number,
    curveParams: Float64Array | number[],
    originX: number,
    originY: number,
    originZ: number,
    xAxisX: number,
    xAxisY: number,
    xAxisZ: number,
    normalX: number,
    normalY: number,
    normalZ: number,
    tStart: number,
    tEnd: number
  ): number;

  // ── Measurement ───────────────────────────────────────────────

  boundingBox(solid: number): Float64Array;

  volume(solid: number, deflection: number): number;

  surfaceArea(solid: number, deflection: number): number;

  faceArea(face: number, deflection: number): number;

  facePerimeter(face: number): number;

  edgeLength(edge: number): number;

  wireLength(wire: number): number;

  centerOfMass(solid: number, deflection: number): Float64Array;

  /** @unwired */
  measureCurvatureAtEdge(edge: number, t: number): Float64Array;

  measureCurvatureAtSurface(face: number, u: number, v: number): Float64Array;

  pointToSolidDistance(px: number, py: number, pz: number, solid: number): Float64Array;

  pointToFaceDistance(px: number, py: number, pz: number, face: number): Float64Array;

  pointToEdgeDistance(px: number, py: number, pz: number, edge: number): Float64Array;

  solidToSolidDistance(a: number, b: number): Float64Array;

  // ── Classification ────────────────────────────────────────────

  /** @unwired */
  classifyPoint(solid: number, x: number, y: number, z: number, tolerance: number): string;

  classifyPointWinding(solid: number, x: number, y: number, z: number, tolerance: number): string;

  classifyPointRobust(solid: number, x: number, y: number, z: number, tolerance: number): string;

  // ── Validation & repair ───────────────────────────────────────

  validateSolid(solid: number): number;

  validateSolidRelaxed(solid: number): number;

  /** @unwired */
  validateSolidWithOptions(solid: number, toleranceScale: number): number;

  healSolid(solid: number): number;

  repairSolid(solid: number): number;

  fixFaceOrientations(solid: number): number;

  mergeCoincidentVertices(solid: number, tolerance: number): number;

  removeDegenerateEdges(solid: number, tolerance: number): number;

  // ── Tessellation ──────────────────────────────────────────────

  tessellateFace(face: number, deflection: number, angularTolerance?: number | null): BrepkitMesh;

  /** @unwired */
  tessellateSolid(solid: number, deflection: number, angularTolerance?: number | null): BrepkitMesh;

  tessellateSolidGrouped(
    solid: number,
    deflection: number,
    angularTolerance?: number | null
  ): string;

  tessellateSolidUV(solid: number, deflection: number, angularTolerance?: number | null): string;

  /** @unwired */
  tessellateEdge(edge: number, numPoints: number): Float64Array;

  /** @unwired */
  meshEdges(solid: number, deflection: number): BrepkitEdgeLines;

  meshEdgesAll(solid: number, deflection: number): BrepkitEdgeLines;

  meshBoolean(
    positionsA: Float64Array | number[],
    indicesA: Uint32Array | number[],
    positionsB: Float64Array | number[],
    indicesB: Uint32Array | number[],
    op: string,
    tolerance: number
  ): BrepkitMesh;

  // ── Export ────────────────────────────────────────────────────

  exportStep(solid: number): Uint8Array;

  exportStl(solid: number, deflection: number): Uint8Array;

  exportStlAscii(solid: number, deflection: number): Uint8Array;

  exportIges(solid: number): Uint8Array;

  export3mf(solid: number, deflection: number): Uint8Array;

  exportObj(solid: number, deflection: number): Uint8Array;

  exportGlb(solid: number, deflection: number): Uint8Array;

  exportPly(solid: number, deflection: number): Uint8Array;

  // ── Import ────────────────────────────────────────────────────

  importStep(data: Uint8Array): Uint32Array;

  importStl(data: Uint8Array): number;

  importIges(data: Uint8Array): Uint32Array;

  import3mf(data: Uint8Array): Uint32Array;

  importObj(data: Uint8Array): number;

  importGlb(data: Uint8Array): number;

  importIndexedMesh(positions: Float64Array | number[], indices: Uint32Array | number[]): number;

  // ── NURBS curves & surfaces ───────────────────────────────────

  interpolatePoints(coords: Float64Array | number[], degree: number): number;

  /** @unwired */
  approximateCurve(
    coords: Float64Array | number[],
    degree: number,
    numControlPoints: number
  ): number;

  approximateCurveLspia(
    coords: Float64Array | number[],
    degree: number,
    numControlPoints: number,
    tolerance: number,
    maxIterations: number
  ): number;

  curveKnotInsert(edge: number, knot: number, times: number): number;

  curveKnotRemove(edge: number, knot: number, tolerance: number): number;

  curveSplit(edge: number, u: number): Uint32Array;

  curveDegreeElevate(edge: number, elevateBy: number): number;

  interpolateSurface(
    coords: Float64Array | number[],
    rows: number,
    cols: number,
    degreeU: number,
    degreeV: number
  ): number;

  approximateSurfaceLspia(
    coords: Float64Array | number[],
    rows: number,
    cols: number,
    degreeU: number,
    degreeV: number,
    numCpsU: number,
    numCpsV: number,
    tolerance: number,
    maxIterations: number
  ): number;

  // ── Sketch ────────────────────────────────────────────────────

  sketchNew(): number;

  sketchAddPoint(sketch: number, x: number, y: number, fixed: boolean): number;

  sketchAddArc(sketch: number, centerIdx: number, startIdx: number, endIdx: number): number;

  sketchAddConstraint(sketch: number, json: string): void;

  sketchSolve(sketch: number, maxIterations: number, tolerance: number): string;

  sketchDof(sketch: number): string;

  // ── 2D polygon ops ────────────────────────────────────────────

  offsetPolygon2d(
    coords: Float64Array | number[],
    distance: number,
    tolerance: number
  ): Float64Array;

  /** @unwired */
  chamfer2d(coords: Float64Array | number[], distance: number): Float64Array;

  /** @unwired */
  fillet2d(coords: Float64Array | number[], radius: number): Float64Array;

  /** @unwired */
  polygonsIntersect2d(coordsA: Float64Array | number[], coordsB: Float64Array | number[]): boolean;

  /** @unwired */
  intersectPolygons2d(
    coordsA: Float64Array | number[],
    coordsB: Float64Array | number[]
  ): Float64Array;

  /** @unwired */
  commonSegment2d(coordsA: Float64Array | number[], coordsB: Float64Array | number[]): Float64Array;

  /** @unwired */
  pointInPolygon2d(polygonCoords: Float64Array | number[], px: number, py: number): boolean;

  // ── Batch & checkpoint ────────────────────────────────────────

  executeBatch(json: string): string;

  checkpoint(): number;

  checkpointCount(): number;

  restore(checkpointId: number): void;

  discardCheckpoint(checkpointId: number): void;

  // ── Assembly ──────────────────────────────────────────────────

  /** @unwired */
  assemblyNew(name: string): number;

  /** @unwired */
  assemblyAddRoot(
    assembly: number,
    name: string,
    solid: number,
    matrix: Float64Array | number[]
  ): number;

  /** @unwired */
  assemblyAddChild(
    assembly: number,
    parent: number,
    name: string,
    solid: number,
    matrix: Float64Array | number[]
  ): number;

  /** @unwired */
  assemblyFlatten(assembly: number): string;

  /** @unwired */
  assemblyBom(assembly: number): string;

  // ── BREP serialization ────────────────────────────────────────

  toBREP(solid: number): string;

  fromBREP(data: string): number;

  // ── Uncategorized ──────────────────────────────────────────────

  /** @unwired */
  convertToBspline(solid: number): number;

  /** @unwired */
  convertToElementary(solid: number): number;

  copyFace(face: number): number;

  /** @unwired */
  detectCoincidentFaces(a: number, b: number): string;

  getNurbsCurveData(edge: number): string;

  /** @unwired */
  getNurbsSurfaceData(face: number): string;

  getNurbsSurfaceDataParity(face: number): string;

  makeCircleEdge(
    cx: number,
    cy: number,
    cz: number,
    nx: number,
    ny: number,
    nz: number,
    radius: number
  ): number;

  /** @unwired */
  makeCircleEdgeWithRef(
    cx: number,
    cy: number,
    cz: number,
    nx: number,
    ny: number,
    nz: number,
    radius: number,
    rx: number,
    ry: number,
    rz: number
  ): number;

  makeEllipseEdge(
    cx: number,
    cy: number,
    cz: number,
    nx: number,
    ny: number,
    nz: number,
    semiMajor: number,
    semiMinor: number
  ): number;

  makeEllipseEdgeWithRef(
    cx: number,
    cy: number,
    cz: number,
    nx: number,
    ny: number,
    nz: number,
    semiMajor: number,
    semiMinor: number,
    rx: number,
    ry: number,
    rz: number
  ): number;

  makePlanarFaceFromWire(wire: number): number;

  offsetWire2DWithJoin(wire: number, distance: number, joinType: string): number;

  /** @unwired */
  sketchAddCircle(sketch: number, centerIdx: number, radius: number): number;

  /** @unwired */
  toBrepJson(solid: number): string;

  transformFace(face: number, matrix: Float64Array | number[]): void;

  // ── Feature-guarded stubs (not in current WASM) ─────────────────

  /** @future Not in brepkit-wasm 2.101.1. Referenced with feature detection in adapter. */
  chamferAsymmetric?(
    solid: number,
    edgeHandles: Uint32Array | number[],
    d1: number,
    d2: number
  ): number;

  /** @future Not in brepkit-wasm 2.101.1. Referenced with feature detection in adapter. */
  compoundFuse?(solidIds: Uint32Array | number[]): number;

  /** @future Not in brepkit-wasm 2.101.1. Referenced with feature detection in adapter. */
  copyEdge?(edge: number): number;

  /** @future Not in brepkit-wasm 2.101.1. Referenced with feature detection in adapter. */
  transformEdge?(edge: number, matrix: Float64Array | number[]): void;

  /** @future Not in brepkit-wasm 2.101.1. Referenced with feature detection in adapter. */
  validateSolidDetails?(solid: number): string;

  // ── wasm-bindgen destructor ────────────────────────────────────

  /** Release the entire arena. */
  free(): void;
}
