// Revolve: a V-groove pulley generated by revolving a 2D profile about the Z axis.
// The profile is drawn in the XZ plane (X = radius, Z = height) and swept a full turn.
import { draw, revolve } from 'brepjs';

const BORE_RADIUS = 4; // mm — central shaft hole radius
const HUB_RADIUS = 18; // mm — outer rim radius
const GROOVE_RADIUS = 12; // mm — depth of the V groove (inner radius)
const HEIGHT = 10; // mm — total axial height
const FULL_TURN = Math.PI * 2; // revolve angle: the occt-wasm kernel reads this in radians

export default () => {
  // Half cross-section, starting at the bore and tracing up the outside,
  // dipping in for the V-groove, and back down to the bore.
  const face = draw([BORE_RADIUS, 0])
    .lineTo([HUB_RADIUS, 0])
    .lineTo([HUB_RADIUS, HEIGHT * 0.25])
    .lineTo([GROOVE_RADIUS, HEIGHT * 0.5])
    .lineTo([HUB_RADIUS, HEIGHT * 0.75])
    .lineTo([HUB_RADIUS, HEIGHT])
    .lineTo([BORE_RADIUS, HEIGHT])
    .close()
    .sketchOnPlane('XZ')
    .face();

  return revolve(face, { axis: [0, 0, 1], at: [0, 0, 0], angle: FULL_TURN });
};
