/**
 * Extracts ```typescript / ```ts code blocks from apps/docs/**\/*.md and emits
 * tests/docs/extracted.test.ts. The generated test file initializes the OCCT
 * kernel once, injects all brepjs exports onto globalThis, then evaluates each
 * snippet inside an AsyncFunction so `await` works.
 *
 * Markers (placed in HTML comments immediately above a fenced block):
 *   <!-- @no-test -->  : skip this block
 *   <!-- @setup -->    : block is hidden setup; prepended to all later snippets in the same file
 *
 * Run via `npm run test:docs` (which calls this first, then vitest).
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, relative } from 'node:path';

const DOCS_DIR = 'apps/docs';
const OUT_DIR = 'tests/docs';
const OUT_FILE = `${OUT_DIR}/extracted.test.ts`;

interface Snippet {
  file: string;
  blockIndex: number;
  startLine: number;
  setup: string;
  code: string;
  skip: boolean;
}

function* walk(dir: string): Generator<string> {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue;
    if (entry.name === 'node_modules' || entry.name === 'public') continue;
    const path = join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(path);
    else if (entry.name.endsWith('.md')) yield path;
  }
}

function lookbackDirective(lines: string[], openIndex: number): { skip: boolean; setup: boolean } {
  let i = openIndex - 1;
  while (i >= 0 && lines[i]?.trim() === '') i--;
  if (i < 0) return { skip: false, setup: false };
  const prev = lines[i] ?? '';
  return {
    skip: prev.includes('<!-- @no-test -->'),
    setup: prev.includes('<!-- @setup -->'),
  };
}

function extractSnippets(file: string): Snippet[] {
  const lines = readFileSync(file, 'utf8').split('\n');
  const snippets: Snippet[] = [];
  let cumulativeSetup = '';
  let blockIndex = 0;
  let i = 0;
  while (i < lines.length) {
    const line = lines[i] ?? '';
    if (/^```(typescript|ts)\b/.test(line.trim())) {
      const codeStart = i + 1;
      let j = codeStart;
      while (j < lines.length && !(lines[j] ?? '').trim().startsWith('```')) j++;
      const code = lines.slice(codeStart, j).join('\n');
      const { skip, setup } = lookbackDirective(lines, i);
      if (setup) {
        cumulativeSetup += (cumulativeSetup ? '\n' : '') + code;
      } else {
        snippets.push({
          file,
          blockIndex: blockIndex++,
          startLine: codeStart + 1,
          setup: cumulativeSetup,
          code,
          skip,
        });
      }
      i = j + 1;
    } else {
      i++;
    }
  }
  return snippets;
}

function generateTestFile(snippets: Snippet[]): string {
  const byFile = new Map<string, Snippet[]>();
  for (const s of snippets) {
    const key = relative(DOCS_DIR, s.file);
    if (!byFile.has(key)) byFile.set(key, []);
    byFile.get(key)?.push(s);
  }

  const blocks = Array.from(byFile.entries())
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([file, list]) => {
      const cases = list
        .map((s) => {
          const label = `${file}:${s.startLine}`;
          const fullCode = (s.setup ? `${s.setup}\n` : '') + s.code;
          const fn = s.skip ? 'it.skip' : 'it';
          return `  ${fn}(${JSON.stringify(label)}, async () => {\n    await runSnippet(${JSON.stringify(fullCode)});\n  });`;
        })
        .join('\n');
      return `describe(${JSON.stringify(file)}, () => {\n${cases}\n});`;
    })
    .join('\n\n');

  return `// AUTO-GENERATED by scripts/extract-doc-tests.ts. Do not edit.
// Regenerate with: npm run docs:extract-tests
/* eslint-disable */
import { beforeAll, describe, it } from 'vitest';
import { initOC } from '../setup.js';
import * as brepjsExports from '@/index.js';

beforeAll(async () => {
  await initOC();
  const g = globalThis as Record<string, unknown>;
  for (const [key, value] of Object.entries(brepjsExports)) {
    if (key !== 'default') g[key] = value;
  }
}, 30000);

const AsyncFunction = Object.getPrototypeOf(async () => {}).constructor as new (
  ...args: string[]
) => (...args: unknown[]) => Promise<unknown>;

function stripImports(code: string): string {
  // Line-by-line strip of ESM import statements. Handles both single-line
  // (\`import { x } from 'y';\`) and multi-line (named imports broken across
  // lines) forms. brepjs exports are injected onto globalThis above, so
  // imports become no-ops in tests.
  const lines = code.split('\\n');
  const out: string[] = [];
  let i = 0;
  while (i < lines.length) {
    const line = lines[i] ?? '';
    if (/^[ \\t]*import\\b/.test(line)) {
      // Consume lines until we find one ending with \`from '...'\` (optionally
      // followed by \`;\`) or until the end of file. Side-effect imports
      // (\`import 'foo';\`) end on the same line.
      let j = i;
      while (j < lines.length) {
        const cur = lines[j] ?? '';
        if (/from\\s+['\"][^'\"]+['\"];?[ \\t]*$/.test(cur)) break;
        if (/^[ \\t]*import\\s+['\"][^'\"]+['\"];?[ \\t]*$/.test(cur)) break;
        j++;
      }
      i = j + 1;
    } else {
      out.push(line);
      i++;
    }
  }
  return out.join('\\n');
}

async function runSnippet(code: string): Promise<void> {
  const stripped = stripImports(code);
  const fn = new AsyncFunction(stripped);
  await fn();
}

${blocks || '// no snippets extracted'}
`;
}

function main(): void {
  const all: Snippet[] = [];
  for (const file of walk(DOCS_DIR)) {
    all.push(...extractSnippets(file));
  }
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT_FILE, generateTestFile(all));
  console.log(`Extracted ${all.length} snippet(s) → ${OUT_FILE}`);
}

main();
