/**
 * Generates docs/kernel-conformance.md from kernel registry and divergence data.
 *
 * Reads kernelConfigs for capability flags and divergences for operation parity,
 * then produces a markdown document with conformance tables.
 *
 * Usage: npx tsx scripts/generateConformance.ts
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { kernelConfigs } from '../tests/helpers/kernelRegistry.js';
import { divergences } from '../tests/helpers/kernelDivergences.js';
import type { Divergence, DivergenceKind } from '../tests/helpers/kernelDivergences.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'docs', 'kernel-conformance.md');

function kindEmoji(kind: DivergenceKind): string {
  switch (kind) {
    case 'not-implemented':
      return '\u274C';
    case 'skip':
      return '\u23ED\uFE0F';
    case 'tolerance':
      return '\u26A0\uFE0F';
    case 'topology-differs':
      return '\uD83D\uDD00';
  }
}

function capEmoji(supported: boolean): string {
  return supported ? '\u2705' : '\u274C';
}

// ---------------------------------------------------------------------------
// Capabilities table
// ---------------------------------------------------------------------------

function generateCapabilitiesTable(): string {
  const capKeys = Object.keys(kernelConfigs[0]!.capabilities) as Array<
    keyof (typeof kernelConfigs)[0]['capabilities']
  >;

  const header = `| Capability | ${kernelConfigs.map((k) => k.displayName).join(' | ')} |`;
  const sep = `| ${'-'.repeat(20)} | ${kernelConfigs.map(() => '-'.repeat(14)).join(' | ')} |`;

  const rows = capKeys.map((cap) => {
    const cells = kernelConfigs.map((k) => capEmoji(k.capabilities[cap]));
    return `| ${cap} | ${cells.join(' | ')} |`;
  });

  return [header, sep, ...rows].join('\n');
}

// ---------------------------------------------------------------------------
// Operation parity table
// ---------------------------------------------------------------------------

function generateParityTable(): string {
  // Collect all divergence keys across all kernels
  const allKeys = new Set<string>();
  const kernelIds = Object.keys(divergences);
  for (const kernelId of kernelIds) {
    for (const key of Object.keys(divergences[kernelId] ?? {})) {
      allKeys.add(key);
    }
  }

  const sortedKeys = [...allKeys].sort();

  // Table header uses kernel display names where available, falling back to id
  const kernelHeaders = kernelIds.map((id) => {
    const cfg = kernelConfigs.find((k) => k.id === id);
    return cfg ? cfg.displayName : id;
  });

  const header = `| Divergence Key | ${kernelHeaders.join(' | ')} |`;
  const sep = `| ${'-'.repeat(40)} | ${kernelIds.map(() => '-'.repeat(20)).join(' | ')} |`;

  const rows = sortedKeys.map((key) => {
    const cells = kernelIds.map((kernelId) => {
      const entry: Divergence | undefined = divergences[kernelId]?.[key];
      if (!entry) {
        return '\u2705';
      }
      const emoji = kindEmoji(entry.kind);
      if (entry.kind === 'tolerance' && 'relativeTol' in entry) {
        const pct = (entry.relativeTol * 100).toFixed(1);
        return `${emoji} ${pct}%`;
      }
      return emoji;
    });
    return `| ${key} | ${cells.join(' | ')} |`;
  });

  return [header, sep, ...rows].join('\n');
}

// ---------------------------------------------------------------------------
// Legend
// ---------------------------------------------------------------------------

function generateLegend(): string {
  return [
    '| Symbol | Meaning |',
    '| ------ | ------- |',
    '| \u2705 | Passing / supported |',
    '| \u274C | Not implemented |',
    '| \u23ED\uFE0F | Skipped (known issue) |',
    '| \u26A0\uFE0F | Tolerance divergence (with percentage) |',
    '| \uD83D\uDD00 | Topology differs |',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const timestamp = new Date().toISOString();

const doc = `# Kernel Conformance Matrix

> Generated: ${timestamp}
>
> Auto-generated by \`npm run conformance:generate\`. Do not edit manually.

## Legend

${generateLegend()}

## Capabilities

${generateCapabilitiesTable()}

## Operation Parity

${generateParityTable()}
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, doc, 'utf-8');

// Script output -- not library code, console is appropriate
// eslint-disable-next-line no-console
console.log(`Wrote ${OUT}`);
